### ISSUE TITLE
Problems with hierarchical keys

### ISSUE THREAD

**Issue by erikogan** [evernote/serge#27] opened 2016-07-27 22:56 UTC
We currently store our translations in YAML files, but I see this being an issue for Java properties, JSON, or any other hierarchical format. 

Ideally, the separator between levels is irrelevant: 

``` yaml
deeply:
  nested:
    key:
      structure: Separators should be irrelevant.
```

It should not matter if this is represented as `deeply.nested.key.structure` or (as Serge represents it) `/deeply/nested/key/structure`.

However, we have some legacy files where many of the keys are _ARE_ the phrase to be translated[*]. The periods have been replaced with underscores, but many of these keys have /’s in their names. I am not sure the best way to proceed. It is not feasible to replace all of these phrases in these files and the code that relies on them[**]. 

I was thinking of looking at making the separator in Serge be configurable (and defaulting to /), but I wanted to ask you your thoughts before I dove into what could potentially be a far-reaching change.

So, any guidance or thoughts you might have on this problem would be appreciated.

[*] This was done with much consternation and hand-wringing to work around a limitation in a service which is no longer relevant.

[**] Though once we have things running through Serge it is likely we will take on a project to work through deprecating them.

**Comment by iafan** [comment] 2016-07-27 23:05
May be I'm missing something, but mere existence of the symbol `/` in the key doesn't immediately mean the file can't be imported. Obviously, this increases a chance of having duplicate keys, but since `serge import` is a one-off thing by design, you can probably manually tweak a couple of strings that cause problems just for the sake of import, and then forget about this import step completely. Do you want to jump to [IRC chat](https://webchat.freenode.net/?nick=web-guest-...&channels=serge&prompt=1&uio=MTE9MzE28) quickly to discuss this? An example of your legacy file might also help me understand the problem better.

**Comment by erikogan** [comment] 2016-07-27 23:09
@iafan Thanks! I need to head out early today. Assuming something does not occur to me overnight, I may need to jump on IRC tomorrow.

**Comment by iafan** [comment] 2016-08-24 18:13
@erikogan Have you been able to import your files and what do you think of this case now? I'd consider this a non-issue (and definitely not justifying implementing a configurable separator) unless you think otherwise and can provide some files that clearly indicate a problem at import time.

**Comment by erikogan** [comment] 2016-08-24 23:09
Sorry, I wrote this about an hour before I left for a weeks vacation. I believe this depends on the serialization backend. PO files key off the source string (with an optional context), and generally only include the original key as a generator comment. So yes, in that case the choice of separator may not be an issue.

However, for another serialization backend (XLIFF 2.0, for example, where a user may want the parser to build the key for them, and/or the parser must pass data through without modification) this will likely become an issue.

Incidentally, I wrote a quick yaml_serializer to help familiarize myself with the serialization backend in preparation for working on an XLIFF seralizer, and also as an attempt to work around a small issue I was facing in the OneSky plugin. It worked perfectly, except in 2 legacy YAML files, which had keys with slashes in them (abbreviated for clarity):

```yaml
en-US:
  "YES": "YES"
  'This is an <a href="%{example_url}">example</a>_html': 'This is an <a href="%{example_url}">example</a>.': 
  "Another <strong>example</strong>_html": "Another <strong>example</strong>."
```

It caused these files to fail to be translated at all, not just the offending keys. This was likely a problem with my yaml_serializer, but it got me thinking about how this should be handled.

I have a PR in the works that will allow a user to configure how they want the keys built, but I’d love your input on the problem as defined above.

**Comment by iafan** [comment] 2016-08-25 23:44
> However, for another serialization backend (XLIFF 2.0, for example, where a user may want the parser to build the key for them, and/or the parser must pass data through without modification) this will likely become an issue.

Please keep in mind that Serge never uses original key as a _unique identifier_; some file formats (like HTML or .master) don't have any notion of keys, so serializers must be aware of that. For .po, Serge generates its own key as a result of `md5_hash(string+separator+context)`, this key is truly unique within any TS file, and should be used to identify the unit within the TS file.

> It caused these files to fail to be translated at all, not just the offending keys. This was likely a problem with my yaml_serializer

Yes, most likely. The way Serge is supposed to deal with the original keys makes it tolerant to any key names. For as long as the source file is a valid one, it should be processed just fine, and even at `serge import` the example above is not supposed to cause any trouble.

When writing your serializer, you don't need to fully resemble the original source file structure. Translation files are inherently different from source files, and should use the simple "array of dictionaries" structure (or its equivalent) wherever possible. The formats chosen for serialization need to be able to pass along at least `key`, `string`, `context`, `comment` and `translation` as separate entities for each unit, and read `translation` field (and optionally, `developer's comment`) at deserialization time.

**Comment by iafan** [comment] 2016-11-30 00:19
It's been a while since we discussed this. I'll close this as an invalid issue for the reasons outlined above, but am happy to follow up on a problem with your specific serializer if your still have this issue.

**Closed by iafan** 2016-11-30 00:19 UTC
