### ISSUE TITLE
[Question] Can serge output translated files to both Android and iOS project folder with different format?

### ISSUE THREAD

**Issue by buptfarmer** [evernote/serge#23] opened 2016-06-29 09:05 UTC
Here is the situation, I have a Project  works both on Android and iOS, I have tested translating my android project with serge+pootle .This is really awesome. 
but how could I output the translated text with iOS format in another output folder which is under the iOS project path.

**Comment by iafan** [comment] 2016-06-29 18:22
My understanding is that you thinking of having one source file in some format, available for translation, and then generate two sets of localized files from it in two different formats. In Serge, handling different formats is much simpler: you can work with two different translation projects having two separate Serge jobs, but sharing the same translation database (to reuse translations across projects).

I would also suggest splitting these jobs into two config files (let's call them `android.serge` and `ios.serge`, respectively) so that you can easily run localization on a separate client only. Each Serge job deals with a separate source directory, separate parser, separate output file naming conventions. In `android.serge` you will have a job that will take your source (e.g. English) Android resource file in XML format and tell Serge to generate localized copies of this file in appropriate resource folders. Similarly, in `ios.serge` you will have a job that will point Serge to your source .strings files, use .strings parser and generate localized copies of these .strings files where you need them.

Jobs in one configuration file and across a multitude of configuration files can still point to the same translation database. Once you translate a string in your Android resource file, the translation will be propagated to the same string appearing in your iOS resource file. With that, you don't have to think about having multiple identical strings in your resources — translating these repetitive strings will be as easy as translating just one string.

Hope this answers the question. For general discussions/questions, I'd recommend joining [#serge IRC channel on Freenode](https://webchat.freenode.net/?nick=web-guest-...&channels=serge&prompt=1&uio=MTE9MzE28).

**Comment by buptfarmer** [comment] 2016-06-30 03:24
I am very grateful for your detailed answer.  I will try that and give feedback soon.   
But actually I don't know different *.po files created by different (Android/iOS) project can share one translation database.  The translation ui in Pootle seems to category the *.po files by path or folder, not by the text need to be translated.  So I sill don't understand how to use one translation database to update translated text which is both in Android and iOS project.    
But I will try it out.

**Comment by iafan** [comment] 2016-06-30 04:12
When talking about the translation database, I mean the internal database Serge uses to store translations and other metadata. Pootle uses its own database. When setting up Serge jobs, you are also telling where to generate the .po files which are then synced to Pootle. Typically, every translation project uses a separate directory for .po files, and these directories are mapped to individual projects inn Pootle. Taking the same example above, your `android.serge` config will have one ore more jobs that will ultimately generate .po files in e.g. `/var/serge/pootle/android/%LOCALE%` folder. And `ios.serge` will generate .po files in e.g. `/var/serge/pootle/ios/%LOCALE%`. Now, Pootle needs to be set up to use `/var/serge/pootle` as its root directory. Then you will set up two projects in Pootle: `android` (which will automatically look up .po files in `/var/serge/pootle/android`) and `ios` (which will automatically look up .po files in `/var/serge/pootle/ios`).

**Comment by buptfarmer** [comment] 2016-07-05 08:15
@iafan   Hi, let me explain my problem again.  
I have a android project  which contains a values.xml file in folder values, it means for default language.

`<resources>

    <string name="app_name">EduGames</string>
    <string name="action_settings">Settings</string>
    <string name="action_feedback">Feedback</string>
</resources>`

After I translated it into other language, take language Japanese as example,

`root@iZ282fwpde2Z:~/02-dev/serge/po# cat values-ja/strings.xml

<resources>
    <string name="app_name">Japan Edu</string>
    <string name="action_settings">設定</string>
    <string name="action_feedback">フィードバック</string>
</resources>`

It works fine till then.  Here is the problem how to reuse the translated text in ios project.
For example, I create an empty ios project with name "ios_project", which has a values.strins like this:

`root@iZ282fwpde2Z:~/02-dev/serge/data_dir/ios_project# cat values.strings

/* comment app_name*/
app_name = "EduGames" // extra comment
/* comment action_settings*/
action_settings = "Settings" // extra comment
/* comment action_feedback*/
action_feedback = "Feedback" // extra comment
/* comment key_in_ios*/
key_in_ios = "value_in_ios" // extra comment`

the texts "EduGames", "Settings" and "Feedback" , they are both in android project and ios project.  I think the ios.serge will reuse the translated text in android project , but it seems wrong, the serge cannot take what I want.  

I hope I have expressed my issue clearly to you this time.

**Comment by iafan** [comment] 2016-07-05 22:17
In your case translations should be definitely reused, provided both your localization jobs share the same database. It would be helpful to see your actual configuration files. Feel free to post them here or send them privately to my email: afan at evernote dot com.

**Comment by buptfarmer** [comment] 2016-07-06 04:19
[android.serge.txt](https://github.com/evernote/serge/files/349044/android.serge.txt)
[ios.serge.txt](https://github.com/evernote/serge/files/349043/ios.serge.txt)

**Comment by buptfarmer** [comment] 2016-07-06 04:25
I use same dababase, with different namespace, ios_project for ios and my_project for android

**Comment by iafan** [comment] 2016-07-06 05:30
I think I know what the problem is: in .strings file format, key-value strings end with semicolon (`;`). In the parser documentation these were missing; you copy-pasted that sample and ended up having a file from which Serge wasn't able to extract any translatable items (you can always check which strings were extracted by looking into the corresponding .po file Serge generates — in your case it contains only the header, but no translation units).

I fixed [the documentation](https://serge.io/docs/plugins/parser/parse_strings/) and also cleaned up your configuration files, externalized common settings into an include file and created a sample setup that works correctly and shares translations between two of your sample projects. I recommend starting with this sample and expanding it as you need.

[Download the example](https://github.com/evernote/serge/files/349117/android_ios.zip)

With this I'm closing the issue as I believe it answers your question. Feel free to reopen it if it doesn't, or go to IRC for additional help.

**Closed by iafan** 2016-07-06 05:30 UTC
Labels: question

**Comment by buptfarmer** [comment] 2016-07-06 06:18
Thanks for your help.  ^_^
